### ISSUE TITLE
Idea to add

### ISSUE THREAD

**Issue by Impre-visible** [enzo-mourany/css-property-sorter#2]
Sometimes, we miss to put the semicolon, it can be great if the extension patch the error when we sort the css, cause there's no error if there's no semicolon at the line before the closing bracket. I hade to repair that for 5 lines, so not a big problem, but will be a good feature. Great work 👏🏻👏🏻

**Comment by enzo-mourany** [comment]
Hi @Impre-visible !

Thanks for your feedback!
I just added this feature to the extension. I will publish a new version soon.
